//
// Generated file, do not edit! Created by nedtool 5.3 from RSUInteraction.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __RSUINTERACTION_M_H
#define __RSUINTERACTION_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0503
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>RSUInteraction.msg:1</tt> by nedtool.
 * <pre>
 * packet RSUInteraction
 * {
 *     string senderRsuId;
 *     string receiverRsuId;
 *     simtime_t sendTime;
 *     simtime_t receiveTime;
 * }
 * </pre>
 */
class RSUInteraction : public ::omnetpp::cPacket
{
  protected:
    ::omnetpp::opp_string senderRsuId;
    ::omnetpp::opp_string receiverRsuId;
    ::omnetpp::simtime_t sendTime;
    ::omnetpp::simtime_t receiveTime;

  private:
    void copy(const RSUInteraction& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const RSUInteraction&);

  public:
    RSUInteraction(const char *name=nullptr, short kind=0);
    RSUInteraction(const RSUInteraction& other);
    virtual ~RSUInteraction();
    RSUInteraction& operator=(const RSUInteraction& other);
    virtual RSUInteraction *dup() const override {return new RSUInteraction(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual const char * getSenderRsuId() const;
    virtual void setSenderRsuId(const char * senderRsuId);
    virtual const char * getReceiverRsuId() const;
    virtual void setReceiverRsuId(const char * receiverRsuId);
    virtual ::omnetpp::simtime_t getSendTime() const;
    virtual void setSendTime(::omnetpp::simtime_t sendTime);
    virtual ::omnetpp::simtime_t getReceiveTime() const;
    virtual void setReceiveTime(::omnetpp::simtime_t receiveTime);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const RSUInteraction& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, RSUInteraction& obj) {obj.parsimUnpack(b);}


#endif // ifndef __RSUINTERACTION_M_H

